# LSP:
# clangd
# cmake-lang: pip3 install cmake-language-server==0.1.4
# bash: npm i -g bash-language-server
# all lsp: https://github.com/helix-editor/helix/wiki/How-to-install-the-default-language-servers

# pylsp: pip3 install python-lsp-server
[[language]]
name = "python"
language-servers = ["pylsp"]

[language-server.pylsp.config.pylsp.plugins]
flake8 = {enabled = true, ignore = ["E501"]}
autopep8 = {enabled = false}
mccabe = {enabled = false}
pycodestyle = {enabled = false}
pyflakes = {enabled = false}
pylint = {enabled = false}
yapf = {enabled = false}
ruff = { enabled = false}

[[languages]]
name = "go"
# formatter = { command = "goimports" }

# cargo install taplo-cli --locked --features lsp
[[language]]
name = "toml"
formatter = { command = "taplo", args = ["fmt", "-"] }
